# Use an official Node.js runtime as a parent image
FROM node:20

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY pnpm-lock.yaml ./
COPY package.json ./

# Install any needed packages specified in package.json
RUN npm install -g pnpm
RUN pnpm install

# Copy the rest of the application code to the working directory
COPY . .

RUN mkdir -p src/types/generated
# Build the React app for production
# Expose port 80 to the outside world
EXPOSE 80

# Command to run the web server
CMD ["pnpm", "dev:docker"]
